- .scrutinizer.yml
- .travis.yml
- phpunit.xml
- src/Math/DebugDecorator.php
- src/Math/Gmp.php
- tests/bootstrap.php
- tests/unit/AbstractTestCase.php
Original GMP adapter used a [custom mod function (see ¤5.1.2)](http://www.matyasdanter.com/2010/12/elliptic-curve-php-oop-dsa-and-diffie-hellman/) to compensate for this [bug](https://bugs.php.net/bug.php?id=52906), which is now fixed.
Also improves the build process by splitting it into smaller tasks (used adapter is defined through an env var in the build matrix), which allows to get quicker feedback on failures.
> Remove non-default mod implementation for GMP adapter

- tests/bootstrap.php
I was just trying to run the whole test suit and ran into this issue.
When you have the xdebug extension loaded it will have a default maximum function level nesting of 100.
This is exceeded in the `NumberTheoryTests` so the tests for that fail.
It can be fixed easily by setting the php ini setting `xdebug.max_nesting_level = 150` (I just guessed 150 would be enough and it worked)
However it thought it might be a good idea to catch this issue before the tests run and notify the user about his bad configuration but still run the actual tests. This PR introduces this change
> Add check to the test bootstrapping for the maximum function level nesting

- bin/phpecc
With php installed through home-brew for example on Mac, the OS version of php is located at /usr/bin/php, and the home-brew version is /usr/local/bin/php.
> Updated the shebang line to allow proper detection of php binary

- src/Console/Application.php
- src/Console/Commands/DumpAsnCommand.php
This implements the logic for the preexisting DumpAsnCommand. You might want to change the exact format in which the ASN.1 objects are displayed but the general logic will probably stay the same.
You can try the command right from a checked out repo using:
```
$ ./bin/phpecc dump-asn --infile tests/data/openssl-priv.key --in der
Sequence : [4 children]
├─Integer : 1
├─Octet String : D3645A981ACF044D86A29EAA6668B969E3266CE61020A880B5144FF863535300
├─[0] Context-specific (0xa0) : [1 child]
├──Object Identifier : Prime256v1 (1.2.840.10045.3.1.7)
├─[1] Context-specific (0xa1) : [1 child]
├──Bit String : 04E553637CF7D3310081A94D6BC2CCF8C9F7F638502E8B2349B03C316566EB8437911F444C3C4700E0DAAB1EB4A0E9D6AC927775578BD3ED6624523EE6C7B6818A
```
> Enable DumpAsnCommand

- src/Console/Commands/DumpAsnCommand.php
- src/CurveFp.php
- src/CurveFpInterface.php
- src/Math/PrimeFieldArithmetic.php
- src/Point.php
- src/PointInterface.php
Original implementation checks that `(cmp(addend->x, augend->x) % curve prime) == 0`.
Considering that cmp returns `0` on equality, a (non specified) negative value if `a < b`, and a (non specified) positive value if `a > b`, `(cmp(addend->x, augend->x) % curve prime) == 0` is true in only three cases:
- `cmp(addend->x, augend->x) == 0`
- `cmp(addend->x, augend->x) == 0 - curve prime` (or any multiple of curve prime)
- `cmp(addend->x, augend->x) == curve prime` (or any multiple of curve prime)
Hence, it's safer to only check that `cmp(addend->x, augend->x) == 0`. I haven't checked the implementation of `gmp_cmp`, but it might as well return randomly a value equal to curve prime (or one of its multiples), leading the point addition code to believe `addend->x == augend->x` are equal, when …
> Refactor add/double operations

- src/Point.php
Bugfix for a minor regression introduced in last P/R:
Direct property access on $addend->x assumes that $addend is an instance of Point, while that may not be always the case (ie. other libraries using this library and providing their own PointInterface implementations).
Ref https://scrutinizer-ci.com/g/mdanter/phpecc/inspections/10d73e9a-118c-4866-9894-95dc0e63ea7a/issues/files/src/Point.php?status=new&orderField=path&order=asc
> Fix access to property on interface hinted variable

- src/Message/EncryptedMessage.php
- src/Serializer/Signature/Der/Formatter.php
- src/Serializer/Signature/Der/Parser.php
- src/Serializer/Signature/DerSignatureSerializer.php
- tests/unit/Serializer/DerSignatureSerializerTest.php
Adds a DerSignatureSerializer. This is the representation openssl will use for signing data. Seems useful to have it here - it was only possible after PHPASN1's Integer class could tolerate big-int's.
> Der signature serializer

- composer.json
- tests/unit/Curves/SpecBasedCurveTest.php
See https://github.com/phpecc/phpecc/pull/116 for background
Had to add to this, as Yaml::parse() no longer accepts file names.
> Allow this library to be used on Symfony3 projects

- src/Serializer/Signature/Der/BignumInt.php
- src/Serializer/Signature/Der/BignumObjectParser.php
- src/Serializer/Signature/Der/Formatter.php
- src/Serializer/Signature/Der/Parser.php
A while ago I patched PHPASN1 with big-integer support, but it looks like that wound up in a php5.6+ branch. This PR adds the Integer class I wrote, and an Object parser patched to use this over the 1.3.1 Integer implementation. 
This PR should fix the test suite, we can jump to the latest PHPASN1 when another version of PHP reaches EOL. 
(There is a tagged branch that includes the Integer class, but it's marked dev, so we'd have to change our minimum compatibility setting)
> Add PHPASN bignum compatibility

- composer.json
Since Console components have moved to `phpecc/console`
> No need for symfony console anymore

- src/Curves/NamedCurveFp.php
- src/Curves/NistCurve.php
- src/Curves/SecgCurve.php
- src/Message/EncryptedMessage.php
- src/Primitives/CurveFp.php
- src/Primitives/CurveFpInterface.php
- src/Primitives/CurveParameters.php
- src/Primitives/Point.php
- tests/unit/Primitives/EcArithmeticTest.php
- tests/unit/Primitives/PointTest.php
As discussed in #97 and #98, point multiplication is not done in constant time which leaks the key through side channel attacks.
This (partially) fixes the issue by introducing a size parameter to perform point multiplication in constant time for a given parameter set.
> Introduce size parameter in curves

- src/Math/NumberTheory.php
- src/Primitives/CurveFp.php
- src/Primitives/CurveFpInterface.php
- src/Serializer/Point/CompressedPointSerializer.php
- tests/unit/Curves/SpecBasedCurveTest.php
Elliptic curve points can be serialized in a compressed notation. The y coordinate can be solved and determined on from only the x-coordinate, and an optionally set bit in the prefix. 
A new method was added to NumberTheory for this: `recoverYfromX`. Also the new class: `CompressedPointSerializer`, which is tested for against each curve/key vector we have for consistence.
I may have stumbled on a bug in NumberTheory developing this since initially, many calls to `squareRootModP` failed. It turned out that method threw upon $a < 0. After removing this check, the method correctly generated the right point.
> CompressedPointSerializer

- .travis.yml
This PR adds test to be performed on the PHP 7 nightly branch.
As it is an unstable branch, the tests are allowed to fail.
> Tests added on the PHP 7 nightly branch

- src/Math/ModularArithmetic.php
- src/Math/NumberTheory.php
- src/Primitives/CurveFp.php
`ModularArithmetic::pow()` was unused throughout the codebase. This PR replaces calls to `GmpMathInterface::powmod()` with the former, as it removes the $prime parameter. Any other occurrences of `mod(fx(), p)` where `fx = add | sub | mul` were replaced in the same way.
> Number theory & CurveFp: use ModularArithmetic

- composer.json
Solve version conflict with other projects by updating the requirement for paragonie/random_compat to a more general "^1|^2".
> Update composer.json to require paragonie/random_compat@"^1|^2"

- src/Serializer/Point/UncompressedPointSerializer.php
- src/Serializer/PublicKey/Der/Formatter.php
- src/Serializer/PublicKey/Der/Parser.php
- src/Serializer/PublicKey/DerPublicKeySerializer.php
- tests/unit/Curves/SpecBasedCurveTest.php
- tests/unit/Serializer/Point/UncompressedPointSerializerTest.php
After removing GmpMath from the `UncompressedPointSerializer`, i also found that the `Serializer\PublicKey\Der\Formatter` no longer had a need for it as its only purpose there was to pass it along the the serializer. Removed it from there aswell. If that was a step to far, let me know.
For the serializer, it was the only dependency so removing it shouldn't cause any issues. php will happily ignore it if you pass it to the constructor anyway. For the formatter it wasn't the only dependency, so removing it there will be a bc-break.
The PR is in two commits atm, one for the serializer and one for the formatter. If you want i can rebase them into one.
> Remove dependency from UncompressedPointSerializer on GmpMath - Resolves #180

- examples/ecdh_exchange.php
- src/Math/NumberTheory.php
- src/Serializer/PrivateKey/DerPrivateKeySerializer.php
- src/Serializer/PrivateKey/PemPrivateKeySerializer.php
- tests/unit/Serializer/PrivateKey/DerPrivateKeySerializerTest.php
This was unused throughout the codebase, but I've changed the type to DerPublicKeySerializer as it should be (it shouldn't be doing anything with PEM there) and made use of the optional parameter in tests.
Fixes #188
> DerPrivateKeySerializer: take DerPublicKeySerializer as a second parameter

- tests/unit/Primitives/PointTest.php
https://blogs.adobe.com/security/2017/03/critical-vulnerability-uncovered-in-json-encryption.html see original PR: #198
> Backport 0.4: Test for invalid points

- composer.json
- src/Serializer/PrivateKey/DerPrivateKeySerializer.php
- src/Serializer/PublicKey/Der/Parser.php
- src/Serializer/Signature/Der/Parser.php
closes #207 (https://github.com/fgrosse/PHPASN1/blob/master/CHANGELOG.md#v200-2017-08)
this should be fully backwards compatible, I don't think anything else uses `Object`. However a new release will be needed for projects depending on this lib.
> Updated to use fgrosse/phpasn1 v2.0

- src/Primitives/GeneratorPoint.php
Since the field isn't required, not one usage of this
function actually passed the order, despite it already
being available on the generator.
This PR removes the optional parameter, and passes the
order of the generator into getPoint
> GeneratorPoint::getPublicKeyFrom() - remove unused parameter

- src/Primitives/GeneratorPoint.php
Since the field isn't required, not one usage of this
function actually passed the order, despite it already
being available on the generator.
This PR removes the optional parameter, and passes the
order of the generator into getPoint
> [0.4] GeneratorPoint::getPublicKeyFrom - remove unused param 

- src/Primitives/Point.php
- tests/unit/Curves/SpecBasedCurveTest.php
- tests/unit/Primitives/PointTest.php
In the conditional swap algorithm, the values A and B
are swapped using a mask whose length is derived from
the bitsize of A or B (taking the largest)
This costs 8 `gmp_strval` AND `BinaryString::length`
operations per run of `Point::cswap`, so 16 per
iteration of the scalar multiplication loop.
The point values X/Y/order (bigints) are swapped,
along with isInfinity (a boolean). The mask for
isInfinity does not depend on the field size, however
X/Y/order have variable size.
This PR makes use of CurveParameters `size` value as
the mask size to avoid excessive string operations on
the values being swapped.
PointTest::testConditionalSwap yielded invalid results
with the change (without modifying the test). Its
unclear where the value of 32 for the size originated.
The test of cswap was a …
> [Backport 0.4] Constant size for mask in conditional swap

- src/Primitives/Point.php
- tests/unit/Curves/SpecBasedCurveTest.php
- tests/unit/Primitives/PointTest.php
In the conditional swap algorithm, the values A and B
are swapped using a mask whose length is derived from
the bitsize of A or B (taking the largest)
This costs 8 `gmp_strval` AND `BinaryString::length`
operations per run of `Point::cswap`, so 16 per
iteration of the scalar multiplication loop.
The point values X/Y/order (bigints) are swapped,
along with isInfinity (a boolean). The mask for
isInfinity does not depend on the field size, however
X/Y/order have variable size.
This PR makes use of CurveParameters `size` value as
the mask size to avoid excessive string operations on
the values being swapped.
PointTest::testConditionalSwap yielded invalid results
with the change (without modifying the test). Its
unclear where the value of 32 for the size originated.
The test of cswap was a …
> Constant size for field element masking in conditional swap

- .gitattributes
would be great if we wouldn't get the examples and tests via composer, when installing with --prefer-dist.
for background see https://www.reddit.com/r/PHP/comments/2jzp6k/i_dont_need_your_tests_in_my_production/
> export ignore doc/examples/tests in distribution

- src/Random/RandomBytesGenerator.php
- src/Random/RandomGeneratorFactory.php
In branch 0.3,` RandomGeneratorFactory::getRandomGenerator` returns `URandomGenerator` which uses `mcrypt_create_iv`, DEPRECATED in PHP 7.1.0, and REMOVED in PHP 7.2.0.
So to force compatibility with PHP >= 7.2.0:
1. created new class `RandomBytesGenerator`
2. added new method `RandomGeneratorFactory::getRandomBytesGenerator`
3. edited `RandomGeneratorFactory::getRandomGenerator` to return `RandomGeneratorFactory::getRandomBytesGenerator` when `random_bytes` function is defined.
> 0.3 - Support PHP v. >= 7.2.0: use 'random_bytes' when available

- src/Random/HmacRandomNumberGenerator.php
Fixes https://github.com/phpecc/phpecc/issues/226
> HmacRandomNumberGenerator: Fix hash length for sha384

- composer.json
- tests/unit/Random/RandomBytesGeneratorTest.php
- tests/unit/Random/URandomNumberGeneratorTest.php
Adds a small test case checking that the classes
return something for the mcrypt and random_bytes
implementations.
The tests can technically fail, because decHex
won't pad the result16 bits, and there's a chance
that one byte would be 0x00, resulting in single
byte of output. It's unlikely, but we don't
generate that many test runs on 0.3
> 0.3: add very simple test for two random number generator classes

- composer.json
Update to a newer version and use a different require pattern. Tests are passing.
Changelogs summary:
- fgrosse/phpasn1 updated from 2.0.1 to 2.1.0
See changes: https://github.com/fgrosse/PHPASN1/compare/2.0.1...2.1.0
Release notes: https://github.com/fgrosse/PHPASN1/releases/tag/2.1.0
> composer: require fgrosse/phpasn1 ^2.0

- .travis.yml
- src/Crypto/Signature/Signer.php
valid range is [1,n-1], had [2,n-1]. Backported from #254
> Backport 0.4: Fix signature verification off by one error
